project_id = "fioykldgrzedxyxpgomf"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.activate-gift-page]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.verify-payment-intent]
verify_jwt = false

[functions.reconcile-payments]
verify_jwt = false

[functions.cleanup-expired-drafts]
verify_jwt = false
